apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ymdragonfly
  namespace: development
spec:
  replicas: 2
  image:
    repository: docker.dragonflydb.io/dragonflydb/dragonfly
    tag: v1.3.1
